source "https://rubygems.org"

gem "jpi"
gem "jenkins-plugin-runtime", "~> 0.2.0"
gem "plist"
gem "require_relative"
gem "test"
gem "pony"
gem "ansi"
gem "jruby-openssl"
gem "maruku"
gem "CFPropertyList"
gem "rubyzip"
